"""empty message

Revision ID: 35ac31e9dfcc
Revises: 693f4cb1e0cc
Create Date: 2026-08-12 10:20:20.336127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ac31e9dfcc'
down_revision = '693f4cb1e0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(), nullable=False))
        batch_op.drop_column('ocupation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocupation', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###
